### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Xcelled**
@logicplace @HanaeN what do you think?

### CODE REVIEW

**Comment by logicplace** [comment]
I think the ews are a bit much but otherwise looks ok to me.

**Review by logicplace — COMMENTED** [review]
I think the ews are a bit much but otherwise looks ok to me.

**Comment by Xcelled** [comment]
Removed ews.

**Review by logicplace — APPROVED** [review]

**Review by HanaeN — APPROVED** [review]
Looks good to me, Well detailed and broken into easy to read sections.

**Pull request merged**
